### ISSUE TITLE
Device Client crashes on Red Hat Enterprise Linux (RHEL) due to SIGILL (Illegal Instruction)

### ISSUE THREAD

**Issue by matthewpaul** [awslabs/aws-iot-device-client#85]
There is a known issue with the 1.0 release of the AWS IoT Device Client in which when running on Red Hat Enterprise Linux (RHEL) as a service, we find that the Device Client service is interrupted by the kernel due to an illegal instruction. After analyzing the core dump from the crash we find the following stack trace:

```
(gdb) bt
#0  0x00007f9b480008d0 in ?? ()
#1  0x0000000000559a14 in get_net_connections_from_proc_buf (net_conns=net_conns@entry=0x7f9b5666c3a0, allocator=allocator@entry=0x1dea900, 
    proc_net_data=proc_net_data@entry=0x7f9b5666c1c0, ifconfig=ifconfig@entry=0x7f9b5666c300, protocol=protocol@entry=AWS_IDNP_TCP)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-c-iot/source/linux/network.c:264
#2  0x000000000055a041 in get_network_connections (net_conns=net_conns@entry=0x7f9b5666c3a0, ifconfig=ifconfig@entry=0x7f9b5666c300, allocator=allocator@entry=0x1dea900)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-c-iot/source/linux/network.c:304
#3  0x0000000000558184 in s_reporting_task_fn (task=0x204f038, userdata=0x204f030, status=<optimized out>)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-c-iot/source/device_defender.c:344
#4  0x0000000000552642 in s_run_all (scheduler=scheduler@entry=0x204e360, current_time=60897996624986, status=status@entry=AWS_TASK_STATUS_RUN_READY)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/task_scheduler.c:249
#5  0x0000000000552b67 in aws_task_scheduler_run_all (scheduler=scheduler@entry=0x204e360, current_time=<optimized out>)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/task_scheduler.c:188
#6  0x00000000004bc727 in s_main_loop (args=0x204ac00)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/linux/epoll_event_loop.c:617
#7  0x000000000055546f in thread_fn (arg=0x1f8eeb0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/posix/thread.c:75
#8  0x00007f9b5838f14a in ?? ()
#9  0x0000000000000000 in ?? ()
```

Based on this stack trace, it appears that the issue is triggered within the Device Defender portion of the SDK, specifically within `network.c`.

**Comment by matthewpaul** [comment]
This issue has now been addressed via the pull requests linked above.
