### ISSUE TITLE
Device Client crashes due to SIGSEGV on Ubuntu x86

### ISSUE THREAD

**Issue by matthewpaul** [awslabs/aws-iot-device-client#86]
There is a known issue with the 1.0 release of the AWS IoT Device Client in which the Device Client, while running as a service, crashes due to a segmentation fault. We were able to analyze the core dump and identify a stack trace here:

```
(gdb) bt
#0  aws_http_message_add_header (message=message@entry=0x0, header=...)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-http/source/request_response.c:592
#1  0x0000000000574de2 in s_new_handshake_request (secure_tunnel=0x7fa558016e80)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-c-iot/source/secure_tunneling.c:292
#2  init_websocket_client_connection_options (secure_tunnel=0x7fa558016e80, 
    websocket_options=websocket_options@entry=0x7fa56681f4d0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-c-iot/source/secure_tunneling.c:309
#3  0x0000000000574ebe in s_secure_tunneling_connect (secure_tunnel=<optimized out>)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-c-iot/source/secure_tunneling.c:329
#4  0x0000000000455a79 in Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingContext::ConnectToSecureTunnel (
    this=0x7fa558019460) at /root/aws-iot-device-client/source/tunneling/SecureTunnelingContext.cpp:104
#5  0x000000000045c381 in Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature::OnSubscribeToTunnelsNotifyResponse (this=0x1552370, response=0x7fa56681fc90, ioErr=0)
    at /root/aws-iot-device-client/source/tunneling/SecureTunnelingFeature.cpp:220
#6  0x000000000046224a in std::_Mem_fn_base<void (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature::*)(Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int), true>::operator()<Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int, void> (this=0x1552960, __object=0x1552370) at /usr/include/c++/5/functional:600
#7  0x00000000004619a3 in std::_Bind<std::_Mem_fn<void (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature::*)(Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int)> (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature*, std::_Placeholder<1>, std::_Placeholder<2>)>::__call<void, Aws::Iotsecuretunneling::SecureTunnelingNoti--Type <RET>--Type--Type--Type <R--Type--T--T--T--T--T--T--Type--T--Type--Type <RET> for more, q to quit, c to continue without paging--
fyResponse*&&, int&&, 0ul, 1ul, 2ul>(std::tuple<Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*&&, int&&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x1552960, __args=...) at /usr/include/c++/5/functional:1074
#8  0x0000000000460907 in std::_Bind<std::_Mem_fn<void (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature::*)(Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int)> (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature*, std::_Placeholder<1>, std::_Placeholder<2>)>::operator()<Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int, void>(Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*&&, int&&) (this=0x1552960) at /usr/include/c++/5/functional:1133
#9  0x000000000045f395 in std::_Function_handler<void (Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int), std::_Bind<std::_Mem_fn<void (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature::*)(Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int)> (Aws::Iot::DeviceClient::SecureTunneling::SecureTunnelingFeature*, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*&&, int&&) (__functor=..., __args#0=@0x7fa56681fc10: 0x7fa56681fc90, 
    __args#1=@0x7fa56681fc0c: 0) at /usr/include/c++/5/functional:1871
#10 0x0000000000570a5e in std::function<void (Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int)>::operator()(Aws::Iotsecuretunneling::SecureTunnelingNotifyResponse*, int) const (__args#1=0, __args#0=0x7fa56681fc90, this=0x1552310) at /usr/include/c++/5/functional:2267
#11 Aws::Iotsecuretunneling::IotSecureTunnelingClient::<lambda(Aws::Crt::Mqtt::MqttConnection&, const String&, const ByteBuf&)>::operator()(const Aws::Crt::ByteBuf &, const Aws::Crt::ByteBuf &, const Aws::Crt::String &, Aws::Crt::Mqtt::MqttConnection &) const (__closure=0x1552310, 
    payload=..., payload=..., this=<optimized out>)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/secure_tunneling/source/IotSecureTunnelingClient.cpp:67
#12 0x000000000048fccf in std::function<void (Aws::Crt::Mqtt::MqttConnection&, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&, aws_byte_buf const&)>::operator()(Aws::Crt::Mqtt::MqttConnection&, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&, aws_byte_buf const&) const (__args#2=..., 
    __args#1="$aws/things/ubuntu-x86/tunnels/notify", __args#0=..., this=0x15525c8) at /usr/include/c++/5/functional:2267
#13 Aws::Crt::Mqtt::MqttConnection::s_onPublish (topic=<optimized out>, payload=0x7fa566820250, userData=0x15525c0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/source/mqtt/MqttClient.cpp:91
#14 0x00000000004a1ecf in s_topic_tree_publish_do_recurse (current_sub_part=current_sub_part@entry=0x7fa56681ff00, current=0x7fa55802dd40, 
    pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:878
#15 0x00000000004a1eb4 in s_topic_tree_publish_do_recurse (current_sub_part=current_sub_part@entry=0x7fa56681ff90, current=0x7fa55802c230, 
    pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:905
#16 0x00000000004a1eb4 in s_topic_tree_publish_do_recurse (current_sub_part=current_sub_part@entry=0x7fa566820020, current=0x7fa55802ca50, 
    pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:905
#17 0x00000000004a1eb4 in s_topic_tree_publish_do_recurse (current_sub_part=current_sub_part@entry=0x7fa5668200b0, current=0x7fa558026050, 
    pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:905
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00000000004a1eb4 in s_topic_tree_publish_do_recurse (current_sub_part=current_sub_part@entry=0x7fa566820140, current=0x7fa55802d170, 
    pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:905
#19 0x00000000004a1eb4 in s_topic_tree_publish_do_recurse (current_sub_part=current_sub_part@entry=0x7fa5668201a0, current=0x7fa55c008000, 
    pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:905
#20 0x00000000004a3602 in aws_mqtt_topic_tree_publish (tree=tree@entry=0x7fa55c007ed8, pub=pub@entry=0x7fa566820220)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/topic_tree.c:922
#21 0x000000000049ef3d in s_packet_handler_publish (connection=0x7fa55c007c80, message_cursor=...)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/client_channel_handler.c:185
#22 0x000000000049e671 in s_process_read_message (handler=<optimized out>, slot=0x7fa55802c570, message=0x7fa558009680)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/client_channel_handler.c:501
#23 0x00000000004ccf0e in s_s2n_handler_process_read_message (handler=0x7fa558011bc0, slot=0x7fa5580095e0, message=<optimized out>)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/s2n/s2n_tls_channel_handler.c:467
#24 0x00000000004c3efe in s_do_read (socket_handler=socket_handler@entry=0x7fa558011ab0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/socket_channel_handler.c:164
#25 0x00000000004c460b in s_on_readable_notification (socket=<optimized out>, error_code=0, user_data=0x7fa558011ab0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/socket_channel_handler.c:221
#26 0x00000000004cbcc4 in s_on_socket_io_event (event_loop=<optimized out>, handle=<optimized out>, events=3, user_data=0x7fa558000bd0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/posix/socket.c:1557
#27 0x00000000004c7240 in s_main_loop (args=<optimized out>)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/linux/epoll_event_loop.c:606
#28 0x000000000056a92f in thread_fn (arg=0x1531ca0)
    at /home/aws-iot-device-client/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/posix/thread.c:75
#29 0x00007fa56724a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#30 0x00007fa56716f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Based on the stack trace above, it appears that the segmentation fault was encountered within the Secure Tunneling portion of the AWS IoT v2 SDK, in which we attempted to add headers related to the Websocket connection to a null instance of a handshake request object.

**Comment by HarshGandhi-AWS** [comment]
This is an old issue which should have been resolved with the latest changes made in C++ SDK. Please reopen this issue if anyone is still seeing this error.
